name: advantage_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  provider: ^6.0.5
  http: ^1.0.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  animate_do: ^4.2.0
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.70.2
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Ad_logo.png
    - assets/images/Amazon-Ads-logo.png
    - assets/images/dell.png
    - assets/images/hdp.png
    - assets/images/ebay.png
    - assets/images/amazon.png
    - assets/images/cisco.png
    - assets/images/bb.png
    - assets/images/ebay_PNG18.png
    - assets/images/bestbuy.png
    - assets/images/woman.png
    - assets/images/man.png
    - assets/images/woman2.png
    - assets/images/woman6.png
